---
apiVersion: v1
kind: Service
metadata:
  name: pxc-node{{.NODEID}}
  labels:
    node: pxc-node{{.NODEID}}
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 4444
    name: state-snapshot-transfer
  - port: 4567
    name: replication-traffic
  - port: 4568
    name: incremental-state-transfer
  selector:
    node: pxc-node{{.NODEID}}
